import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./ui/navbar";
import Transition from "./ui/transition";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MEBotto Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Transition>{children}</Transition>
      </body>
    </html>
  );
}
